### ISSUE TITLE
Starting the project

### ISSUE THREAD

**Issue by ZaidMinhas** [ZaidMinhas/OurDreamTeam#1]
# Plan
The plan is to recreate Dream Team with local co-op instead of online multiplayer, though hopefully I'll be able to implement it in the future.

The game will also be lacking on the visual side since I am mainly a programmer, but I will try recruiting people after finishing all my to-dos

# to-do
- [ ] Create players movements
- [ ] Create Weapons
- [ ] Weapon Combos
- [ ] Enemies
- [ ] Create House
- [ ] Dream Cores
- [ ] Level System
- [ ] UI, audio, graphical improvements

**Comment by ZaidMinhas** [comment]
# Create players movements

- [ ] Controller and Keyboard n Mouse movements
